sudo: required
dist: trusty

# Tricks to avoid unnecessary cache updates
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.ivy2/local
    - $HOME/.sbt/boot

# dependencies for integration tests
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - gcc-4.8
      - g++-4.8
      - libstdc++6-4.6-dev
      - libboost1.55-dev

env:
  global:
    - CXX="g++-4.8"
    - CC="gcc-4.8"
    - secure: YHeBrU79+CwP5VCsX57b+T94ppeTBC2EWgRmtYV/XksUrqJlEphEiMHJl2axMUzBy3BES+IjUuwxe4rkPtkj/lE0md0n1JXhbhzq1s6kTjb3qOmaBrWGZKzhRo5S5FcjBoTbm7k9YeHRHztGzeTJnpLFYpTWLLLoWhH8rXxBWrN2gmn6dMYWS1j1jYpLkaCHqLpAhRW333k63nrK+nq+cGUWOTi/FVQoCq29agX1n2xmj7yDnZpt21t7eNSYT2AqnJHw96JTblbMYIZbocCNcEqfKS1SBCxE7572w8aZzFI517AjCSas7F/wOqmY8hdua5KwhKOIApuhU79rnHmXHkwvBNdoCCc1MlWnWYtISRNTjgL2SIpd5rfcX2g99XsLK8PbU9I6tfstL6kvMkB/NFEZ46XHTNgJxrFSD6tGA5upulq02pZogOP/Ejx7/7qwQE6Exr3vpGkyhTkho+XhoTqATnPnJy/ZvDFPuoGqqoKR8wKnFHLkaAytz5gZqrvmlEn85+r9fK888Nhk07E0eVik+2VU3Wzp4oygMGOOmBmZnYIJqrcNpPgIJr0VAdAhbVNvspJICPhXqAOCSOnDq5v/goP2iM1B78BcA2LljtZJBplhegvb674dCsws0dxpDKIQjnd+0tw/NWV4F4tfwcIqk4XnkPgsiYb9vdQe7K0=
    - secure: r0b3pEJza71w2U3+0nQSH6WLotNVHQiVc3OeCsVQbI74CF/AMJS0JogSfmOMw6dUNFMvDdU1FQd+goD1tt31h5ATNK5RIFiVhiKiSKyOMzVaMByUbTjVtnmPj9ZO+CsyqkkdnFHk7C7HFld5sY5lElHXJ9UhOkZJRhqlJJYsrTZdmf11O2AIfMToOLS77j44nNBmwvviIytxTnBvbeQNBUQ/4jATHjHl6wvc9XfoBYl1s5yYtaJul5cILt8t7nvxqIB4+o4MjAnfps+Q8lRgPBk8XAaup55qLPt/YSemgCEPVrb3rDKUsh7MwLtgHtLLEi6c9D/TVJXhAvSXDInNb+zTvWX9M1u0ZjronXATiu9yE3kLyTvf2n2uZTarfYWfT1NWuKl4KdvgBdXHj5WtFYA34K2J7cXA+0O+6bf7OyzkPshNpze/HUaD5OBsp1ussXd//CxBQXm3wDlkWEWE4q0n9crLLnl0UHGlRFmf3JOhjp3w6L3etJ0gwHYc7fC/HAckt47CteCwllrg0QjbJCa1ZUkUj+vHN95RuKRa0G5x/JK/LuiCTj0NtEmOmM4LjljNJ5UIPtfAxREME9XpcH+fS3K/PZm2hLE/NOh53WrdvjnJYhR7CBIhCyKJfGLyy3GrzOusu2InQbZyTn3q92iT7S+VpbreJW5lJTVs3Y0=
  matrix:
    - TEST_SUITE=test
#    - TEST_SUITE=it:test

language: scala

jdk:
  - oraclejdk8

install:
  - if test ! -d "$HOME/.ivy2/local/org.scala-lang.lms"; then
      git clone "https://github.com/scalan/virtualization-lms-core.git" &&
      (cd virtualization-lms-core && sbt publishLocal);
    fi

script:
  - sbt -jvm-opts .travis.jvmopts $TEST_SUITE

after_success:
  - sbt -jvm-opts .travis.jvmopts publish
