sudo: required
dist: trusty

# Tricks to avoid unnecessary cache updates
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.ivy2/local
    - $HOME/.sbt/boot

# dependencies for integration tests
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - gcc-4.8
      - g++-4.8
      - libstdc++6-4.6-dev
      - libboost1.55-dev

env:
  global:
    - CXX="g++-4.8"
    - CC="gcc-4.8"
    - secure: YHeBrU79+CwP5VCsX57b+T94ppeTBC2EWgRmtYV/XksUrqJlEphEiMHJl2axMUzBy3BES+IjUuwxe4rkPtkj/lE0md0n1JXhbhzq1s6kTjb3qOmaBrWGZKzhRo5S5FcjBoTbm7k9YeHRHztGzeTJnpLFYpTWLLLoWhH8rXxBWrN2gmn6dMYWS1j1jYpLkaCHqLpAhRW333k63nrK+nq+cGUWOTi/FVQoCq29agX1n2xmj7yDnZpt21t7eNSYT2AqnJHw96JTblbMYIZbocCNcEqfKS1SBCxE7572w8aZzFI517AjCSas7F/wOqmY8hdua5KwhKOIApuhU79rnHmXHkwvBNdoCCc1MlWnWYtISRNTjgL2SIpd5rfcX2g99XsLK8PbU9I6tfstL6kvMkB/NFEZ46XHTNgJxrFSD6tGA5upulq02pZogOP/Ejx7/7qwQE6Exr3vpGkyhTkho+XhoTqATnPnJy/ZvDFPuoGqqoKR8wKnFHLkaAytz5gZqrvmlEn85+r9fK888Nhk07E0eVik+2VU3Wzp4oygMGOOmBmZnYIJqrcNpPgIJr0VAdAhbVNvspJICPhXqAOCSOnDq5v/goP2iM1B78BcA2LljtZJBplhegvb674dCsws0dxpDKIQjnd+0tw/NWV4F4tfwcIqk4XnkPgsiYb9vdQe7K0=
    - secure: dNDMiR/5EXtFLncKsAST5FKXNwBN/wvV4vLHnjs7h+2vxwXs/hnwow6z12BN+yrLJVFuTYNQbzCSrYnSutdUEmI8YCx66OuPnNfCSMlajT7bJBC9PzGP+Mmsf6ZNGeaZDWKPyKouabbfBbBZbxIzSjUiZSFo/27NPDBau8fSEd6Kk+1qbxITraCz2hv1ZaHmJWrcGd32hcn5rufRySwsbGgo+jCR5Y+kesbOuGbtnfpu4R4/5t2AJNkXLfXcLDyq9yaFQONKTWqb8Yn/ea7Dc09GDqnWgaNZwhbIJhi4+vm/RLjNqZHelwYvkTX2hIiKe4y0DJGlvt2Xntw3frQ4u3CnHlqFz8VXuzhcqi8xvVlGypE5R9pl+fVbGjPnTewL7jogaBE535TAFXAziee74KuUnB/j7rbPKrl0uhSK60sEsagNGcjE+A1wY8OBnnZv0YN0+UUdGuDrNUBCnGc8853cV7yjqUWEgG9hVNClhgNXSn1gZSj4rr+tdsRoT54IFHTUsinGBS2/NT0EvYj9wzWdyI6i7yt77OYyRkHcmTTxPU6fMHxn5R2RycDo1htIN7ImwM69jjDWxFtjPnxmqVir+he7oI0lvZ+ASGrMAKWISkan3329WQLwSDdDvgXZO+Fi5SMUwd7T+Ka5eK3t3PBVehX+lilqX86PhDwHqLo=
  matrix:
    - TEST_SUITE=test
#    - TEST_SUITE=it:test

language: scala

jdk:
  - oraclejdk8

install:
  - if test ! -d "$HOME/.ivy2/local/org.scala-lang.lms"; then
      git clone "https://github.com/scalan/virtualization-lms-core.git" &&
      (cd virtualization-lms-core && sbt publishLocal);
    fi

script:
  - sbt -jvm-opts .travis.jvmopts $TEST_SUITE

after_success:
  - sbt -jvm-opts .travis.jvmopts publish
